{% set version = "4.6.8" %}

package:
  name: kombu
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kombu/kombu-{{ version }}.tar.gz
  sha256: 2d1cda774126a044d91a7ff5fa6d09edf99f46924ab332a810760fe6740e9b76

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - importlib_metadata >=0.18  # [py<=37]
    - amqp >=2.5.2,<2.6

test:
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Messaging library for Python
  dev_url: https://github.com/celery/kombu
  doc_url: https://kombu.readthedocs.org

extra:
  recipe-maintainers:
    - anguslees
    - kwilcox
    - pmlandwehr
    - igortg
