{% set name = "kombu" %}
{% set version = "5.3.0a1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kombu-{{ version }}.tar.gz
  sha256: 02f3258b75c967586418e10942a14996900a04c62ea23252b4b4d3dd5c6d81ab

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - pytest
    - python
  run:
    - amqp >=5.1.1,<6.0.0
    - cached-property  # [py<38]
    - importlib-metadata >=0.18  # [py<38]
    - python
    - vine
    - typing-extensions

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.io
  summary: Messaging library for Python.
  doc_url: https://pythonhosted.org/kombu/
  dev_url: https://github.com/celery/kombu
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - anguslees
    - kwilcox
    - igortg
