{% set name = "kombu" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kombu-{{ version }}.tar.gz
  sha256: af17a0ab0c7508dd50cc9d1378d0cf68566a953fca8aaae4e8dab107a79aa440

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - amqp >=5.0.6,<6.0.0
    - cached-property  # [py<38]
    - importlib-metadata >=0.18  # [py<38]
    - python
    - vine

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.io
  summary: Messaging library for Python.
  doc_url: https://pythonhosted.org/kombu/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - anguslees
    - kwilcox
    - pmlandwehr
    - igortg
