{% set name = "kombu" %}
{% set version = "5.5.1" %}
# Latest python_min is defined in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kombu-{{ version }}.tar.gz
  sha256: a4c2250396cdfb947c5e5322f3094fd36c3f86a1cff655f5cffdf45f371dddb8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - amqp >=5.1.1,<6.0.0
    - typing_extensions  # strictly, py<310
    - python >={{ python_min }}
    - vine
    - boto3 >=1.26.143  # for sqs

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.io
  summary: Messaging library for Python.
  doc_url: https://pythonhosted.org/kombu/
  dev_url: https://github.com/celery/kombu
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - anguslees
    - kwilcox
