{% set name = "kombu" %}
{% set version = "5.5.0" %}
# Latest python_min is defined in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kombu-{{ version }}.tar.gz
  sha256: 72e65c062e903ee1b4e8b68d348f63c02afc172eda409e3aca85867752e79c0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    # See https://pypi.org/pypi/kombu/{{ version }}/json
    # Only enforce lower constraints of exact versions, per https://iscinumpy.dev/post/bound-version-constraints/
    - amqp >=5.1.1,<6.0.0
    - typing_extensions >=4.12.2  # strictly, ==4.12.2 py<310. See https://github.com/celery/kombu/pull/2274
    - vine >=5.1.0 # strictly, ==5.1.0
    - python-tzdata >=2025.1 # strictly, ==2025.1. See https://github.com/celery/kombu/issues/2272
    - boto3 >=1.26.143  # for sqs option

test:
  requires:
    - python {{ python_min }}
    - pip
    - mypy ==1.14.1
  source_files:
    - setup.cfg
  commands:
    # - pip check
    - set -o posix ; set
    - python -m mypy -p kombu --config-file setup.cfg
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.io
  summary: Messaging library for Python.
  doc_url: https://pythonhosted.org/kombu/
  dev_url: https://github.com/celery/kombu
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - anguslees
    - kwilcox
    - jamesmyatt
