{% set version = "4.6.10" %}

package:
  name: kombu
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kombu/kombu-{{ version }}.tar.gz
  sha256: 437b9cdea193cc2ed0b8044c85fd0f126bb3615ca2f4d4a35b39de7cacfa3c1a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - importlib_metadata >=0.18  # [py<=37]
    - amqp >=2.6.0,<2.7

test:
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Messaging library for Python
  dev_url: https://github.com/celery/kombu
  doc_url: https://kombu.readthedocs.org

extra:
  recipe-maintainers:
    - anguslees
    - kwilcox
    - pmlandwehr
    - igortg
