{% set name = "kombu" %}
{% set version = "5.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kombu-{{ version }}.tar.gz
  sha256: d084ec1f96f7a7c37ba9e816823bdbc08f0fc7ddb3a5be555805e692102297d8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - pytest
    - python
  run:
    - amqp >=5.1.1,<6.0.0
    - backports.zoneinfo >=0.2.1    # [py<39 or python_impl == "pypy"]
    - tzdata  # [py<39 or python_impl == "pypy"]
    - typing_extensions  # [py<310]
    - python
    - vine

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.io
  summary: Messaging library for Python.
  doc_url: https://pythonhosted.org/kombu/
  dev_url: https://github.com/celery/kombu
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - anguslees
    - kwilcox
    - igortg
