{% set name = "kombu" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kombu-{{ version }}.tar.gz
  sha256: 01481d99f4606f6939cdc9b637264ed353ee9e3e4f62cfb582324142c41a572d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - amqp >=5.0.6,<6.0.0
    - cached-property  # [py<38]
    - importlib-metadata >=0.18  # [py<38]
    - python
    - vine

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://kombu.readthedocs.io
  summary: Messaging library for Python.
  doc_url: https://pythonhosted.org/kombu/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - anguslees
    - kwilcox
    - pmlandwehr
    - igortg
